### ISSUE TITLE
Error on calling splitAndCamelCase

### ISSUE THREAD

**Issue by stephanieder** [diya-sdk/diya-sdk-status#4]
Calling the method getStatus from the status_handler return this error

Seen when calling this method from an Application (Diya-VIP Application).

```
"TypeError: inString.split is not a function
    at Status.splitAndCamelCase (https://localhost/vip/bower_components/diya-sdk-status/build/status.min.js:1:20816)
    at https://localhost/vip/bower_components/diya-sdk-status/build/status.min.js:1:19182
    at Object.callback (https://localhost/vip/bower_components/diya-sdk/build/diya-sdk.min.js:2:5275)
    at DiyaNode._notifyListener (https://localhost/vip/bower_components/diya-sdk/build/diya-sdk.min.js:1:25011)
    at DiyaNode._handleRequest (https://localhost/vip/bower_components/diya-sdk/build/diya-sdk.min.js:1:28900)
    at DiyaNode._onmessage (https://localhost/vip/bower_components/diya-sdk/build/diya-sdk.min.js:1:26079)
    at SocketHandler.EventEmitter.emit (https://localhost/vip/bower_components/diya-sdk/build/diya-sdk.min.js:1:5201)
    at SocketHandler._onmessage (https://localhost/vip/bower_components/diya-sdk/build/diya-sdk.min.js:1:31693)"
```

**Comment by stephanieder** [comment]
Resolved in the application itself, closing
